package app54;

public class M30 {
	public static void main(String[] args) {
		try {
			
		}
		catch(ArithmeticException ex) {
			
		}
		System.out.println(1);
	}
}
//this is possible b/c try is not alone try with the catch